version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuebolt_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - cuebolt_network

  mysql:
    image: mysql:8.0
    container_name: cuebolt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuebolt
      MYSQL_USER: cuebolt_user
      MYSQL_PASSWORD: cuebolt_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    networks:
      - cuebolt_network

  nginx:
    image: nginx:latest
    container_name: cuebolt_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cuebolt_network

volumes:
  mysql_data:

networks:
  cuebolt_network:
    driver: bridge
